[functions.schlaf-import]
verify_jwt = false

[functions.fokus]
verify_jwt = false

[functions.push-test]
verify_jwt = true

[functions.schlaf-erinnerung]
verify_jwt = true

[functions.gewicht-erinnerung]
verify_jwt = true
